import type { ExerciseCategory } from '@/types';

export const eliteStateManagementCategory: ExerciseCategory = {
  id: 'elite-state-management',
  name: 'Elite State Management',
  description: 'Master advanced state patterns combining discriminated unions with useReducer and Redux architecture',
  icon: 'IconBrain',
  order: 3,
  exercises: [
    {
      id: '01-usereducer-patterns',
      title: 'useReducer with Discriminated Union Patterns',
      description: 'Master advanced state management by combining useReducer with discriminated unions for type-safe, scalable, and predictable state transitions',
      category: 'elite-state-management',
      difficulty: 5,
      prerequisites: ['discriminated-unions', 'react-hooks'],
      learningObjectives: [
        'Combine discriminated unions with useReducer for type-safe actions',
        'Design complex state machines with predictable transitions',
        'Implement async operations with discriminated union states',
        'Create reusable reducer patterns for different domains',
        'Handle error states and loading patterns elegantly',
        'Build undo/redo functionality with discriminated unions',
      ],
      hints: [
        'Always define discriminated unions for both state and actions',
        'Use exhaustive checking with `never` type for complete coverage',
        'Keep reducers pure - no side effects or mutations',
        'Use immer for complex state updates if needed',
        'Implement state machine guards for valid transitions',
        'Create action creators for better ergonomics',
      ],
      estimatedTime: 45,
      filePath: './exercise-files/elite-state-management/01-usereducer-patterns/exercise.ts',
      solutionPath: './src/exercises/elite-state-management/01-usereducer-patterns/solution.ts',
      testsPath: './src/exercises/elite-state-management/01-usereducer-patterns/tests.ts',
      instructionsPath: './src/exercises/elite-state-management/01-usereducer-patterns/instructions.md',
    },
    {
      id: '02-redux-discriminated-patterns',
      title: 'Redux with Discriminated Union Actions',
      description: 'Build scalable Redux applications using discriminated unions for actions and state management',
      category: 'elite-state-management',
      difficulty: 5,
      prerequisites: ['01-usereducer-patterns'],
      learningObjectives: [
        'Implement Redux with discriminated union action types',
        'Design normalized state with discriminated unions',
        'Create type-safe action creators and selectors',
        'Handle complex async flows with Redux Toolkit',
        'Implement optimistic updates with rollback patterns',
        'Build real-time synchronization with state machines',
      ],
      hints: [
        'Use Redux Toolkit for better developer experience',
        'Normalize your state shape for better performance',
        'Create typed hooks for dispatching and selecting',
        'Use discriminated unions for different entity states',
        'Implement middleware for complex async patterns',
        'Consider using RTK Query for data fetching',
      ],
      estimatedTime: 50,
      filePath: './exercise-files/elite-state-management/02-redux-discriminated-patterns/exercise.ts',
      solutionPath: './src/exercises/elite-state-management/02-redux-discriminated-patterns/solution.ts',
      testsPath: './src/exercises/elite-state-management/02-redux-discriminated-patterns/tests.ts',
      instructionsPath: './src/exercises/elite-state-management/02-redux-discriminated-patterns/instructions.md',
    },
    {
      id: '03-advanced-state-machines',
      title: 'Advanced State Machines with XState',
      description: 'Build complex state machines using XState with discriminated unions for bulletproof state management',
      category: 'elite-state-management',
      difficulty: 5,
      prerequisites: ['01-usereducer-patterns', '02-redux-discriminated-patterns'],
      learningObjectives: [
        'Model complex business logic as state machines',
        'Integrate XState with React and TypeScript',
        'Design hierarchical and parallel state machines',
        'Implement guards, actions, and activities',
        'Handle machine-to-machine communication',
        'Test state machines comprehensively',
      ],
      hints: [
        'Start with simple machines and build complexity gradually',
        'Use the XState visualizer to understand machine behavior',
        'Leverage TypeScript for better machine typing',
        'Consider using services for async operations',
        'Use hierarchical states for complex UI flows',
        'Test all possible state transitions thoroughly',
      ],
      estimatedTime: 55,
      filePath: './exercise-files/elite-state-management/03-advanced-state-machines/exercise.ts',
      solutionPath: './src/exercises/elite-state-management/03-advanced-state-machines/solution.ts',
      testsPath: './src/exercises/elite-state-management/03-advanced-state-machines/tests.ts',
      instructionsPath: './src/exercises/elite-state-management/03-advanced-state-machines/instructions.md',
    },
  ],
};